# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YjiLocationClock' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
pod 'GoogleMaps'
pod 'SnapKit'
pod 'EasyTipView', '~> 1.0.2'
pod 'GooglePlaces'
pod 'GooglePlacePicker'

end

